name: untitled
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.3.1

  # State & utils
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  provider: ^6.1.2
  get_it: ^7.7.0
  # JSON annotations (runtime)
  json_annotation: ^4.9.0

  # Files, paths, zipping
  path_provider: ^2.1.4
  path: ^1.9.0
  archive: ^3.6.1

  # Media & permissions
  image_picker: ^1.1.2
  permission_handler: ^11.3.1

  # Storage & misc
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

  # UI
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

  # Firebase (optional—only if you actually use them)
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0

  # Add only if you explicitly set MultipartFile contentType
  # http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation (dev only)
  build_runner: ^2.4.12
  json_serializable: ^6.9.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
